### ISSUE TITLE
有没有sql文件

### ISSUE THREAD

**Issue by wujieliu** [itachizhu/cms#1]
有没有sql文件

**Comment by itachizhu** [comment]
这个只是一个架构示例，你可要通过DTO和来参考建立对应的数据库表即可。
主要记录响应的框架和spring-boot、spring-cloud的使用和对整个框架的分层把握的。
谢谢你的关注，我们后面会根据joomla来开发一个类似的系统，敬请期待。

**Comment by itachizhu** [comment]
这个只是一个架构示例，你可要通过DTO和来参考建立对应的数据库表即可。
主要记录响应的框架和spring-boot、spring-cloud的使用和对整个框架的分层把握的。
谢谢你的关注，我们后面会根据joomla来开发一个类似的系统，敬请期待。
